config/routes.rb
Rails.application.routes.draw do
  resources :offers
  root to: 'offers#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/license.rb
class License < ApplicationRecord
  validates :license_key, length: { maximum: 10 }
  validates :offer, presence: true
  belongs_to :offer
end

app/models/offer.rb
class Offer < ApplicationRecord
  validates :title, :decription, presence: true
  validates :title, :decription, length: { maximum: 20 }
  has_one :license, dependent: :destroy

  accepts_nested_attributes_for :license, :allow_destroy => true
  before_validation :mark_tour_dates_for_destruction

  def mark_tour_dates_for_destruction
    license.mark_for_destruction if license.license_key.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
    @offer.build_license
  end

  # GET /offers/1/edit
  def edit
    @offer.build_license if @offer.license.blank?
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:title, :decription, license_attributes: :license_key)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Treat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/offers/_form.html.erb
<%= form_with(model: offer, local: true) do |form| %>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :offer_title %>
  </div>

  <div class="field">
    <%= form.label :decription %>
    <%= form.text_area :decription, id: :offer_decription %>
  </div>

  <div class="field">
  <%= form.fields_for :license do |l| %>
    <%= l.label :license_key, "License key" %>
    <%= l.text_field :license_key %>
  <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form', offer: @offer %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Decription</th>
      <th>License</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.title %></td>
        <td><%= offer.decription %></td>
        <td><%= offer.license.license_key if offer.license.present? %></td>
        <td><%= link_to 'Show', offer %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new.html.erb
<h1>New Offer</h1>

<%= render 'form', offer: @offer %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @offer.title %>
</p>

<p>
  <strong>Decription:</strong>
  <%= @offer.decription %>
</p>

<p>
  <strong>License:</strong>
  <%= @offer.license.license_key if @offer.license.present? %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>